services:
  app:
    container_name: backend
    image: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    networks:
      - mongo
    volumes:
      - ./backend/:/src/app
      - /src/app/node_modules
      
    
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
    networks:
      - mongo
    volumes:
      - ./mongo:/data/db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    restart: always


  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend  
      dockerfile: Dockerfile 
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app 
      - /frontend/node_modules
      - /frontend/.next
    networks:
      - mongo 

networks:
  mongo:
    external: true