services:
  app:
    container_name: backend
    image: backend
    build: 
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - mongo
    volumes:
      - .:/scr/app
      - /scr/app/node_modules
    
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
    networks:
      - mongo
    volumes:
      - ./mongo:/data/db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

networks:
  mongo:
    external: true


